### ISSUE TITLE
remove ternary operators, reduce redundance . improvements

### ISSUE THREAD

**Issue by michelerenzullo** [bfraboni/FastGaussianBlur#6]
in horizontal_blur_extended (same pattern should work for ..._crop as well)

1) Removed ternary operator in initial accumulation
2) Reduced constant redundant calculation in "initial accumulation"
3) Reduced constant redundant calculation in "perform filtering loop"

TODO: 
remove ternary operator inside "perform filtering loop", a bit harder in this case

gist here, read comments :)
https://gist.github.com/michelerenzullo/89a047422fc0c0fc2f57432b80383676

**Comment by bfraboni** [comment]
Ok, so here what I did in the last commit c44fbc20dd37a0f75abc7e483df4aa885d6db9d4 in the main branch (forgot to reference the issue in the commit message):

1. Did not, since it does not seem improve performances, even for large values of r.
2. Did it.
3. Did it.
4. (TODO) Did it but in a particular way: I split the `horizontal_blur_extend` function in two distinct functions, one for small kernels and one for large kernels. I also modified the dispatcher such that it calls the right function when the kernel radius is larger that the image width, `r > w`, and conversely. The large kernel version updates the accumulator with only `lv` and `fv` values which is fast without ternary operations. 
https://github.com/bfraboni/FastGaussianBlur/blob/c44fbc20dd37a0f75abc7e483df4aa885d6db9d4/fast_gaussian_blur_template.h#L174
The small kernel version has been changed such that the filter loop is divided in 3 loops that allow to remove the ternary operations too (this is what I pushed in the unsafe branch, plus the improvements from point 2 and 3). https://github.com/bfraboni/FastGaussianBlur/blob/c44fbc20dd37a0f75abc7e483df4aa885d6db9d4/fast_gaussian_blur_template.h#L118
This way, both functions are optimized depending on the kernel size. Note that I also kept the original generic version with modifications 2 and 3. https://github.com/bfraboni/FastGaussianBlur/blob/c44fbc20dd37a0f75abc7e483df4aa885d6db9d4/fast_gaussian_blur_template.h#L72

This gives me the best performances I have seen on my laptop: ~350ms for a 8k * 4k image with arbitrary kernel sizes (tried 20, 200, 2000, 4000, 6000).

Please try the last version on the main branch, and let me know if the performances are good for your use case too.

**Comment by michelerenzullo** [comment]
Nice , I will test, for some reason the first point "did not" , I agree 

1) for the initial accumulation, pre fill the accumulation outside the loop, plus skipping the ternary operator, it seems to not improve the performance I agree , this is strange tho, since is repeating the same calculation for every i in height . Any thoughts? Should be better in theory . R has to be wider than w to spot the speedup, so in your test with 8000x4000 only the kernel size 6000 is good for comparison, the others won't spot the difference I guess 

I might have some new thoughts since we iterate 2 (or more times) the algorithm, about "double accumulation" at once . But I will think more on it before write

**Comment by bfraboni** [comment]
Note that `r` is just the filter radius, so the filter size is `2*r+1`. Therefore when sigma equals 2000 or more the filter is always wider than the 4k height.

My guess regarding point 1 is that the condition `j<w` is simple enough such that the compiler is capable of splitting the initial accumulation loop into two loops to remove the ternary completely.
Furthermore since the second loop would only add `lv` a certain number of times, it can probably replace the second loop by a multiplication as we tried to do by hand.
I'm not sure though, I'll check on godbolt the generated code tomorrow.

It often happens to me to see a simple 1 line loop being super optimized automatically by the compiler. And it already happened that a 2 line loop of size N split into two 1 line loops of the same size being 30% faster on my ryzen 7 2700x, which is super counter intuitive.

**Comment by michelerenzullo** [comment]
I will check further, oh sorry for kernel size I meant double of the radius.

**Comment by michelerenzullo** [comment]
With this benchmark show that filling the preaccumulation is faster, but in your code I don't spot differences. The compiler is so smart? I'm not so sure

```c++
#include <iostream>
#include <chrono>

void fill()
{
	srand(time(NULL));
	int r = 2 * 100000, w = 100000, h = 10000;

	int fill = 0; // reduce redundant calculation when extending the border, we set (r-w) "how many times add lv[ch]"
	if (r > w)
		fill = (r - w);

	for (int i = 0; i < h; i++)
	{

		int acc;
		acc = fill * 55 + 66; // added fill[ch] * lv[ch] for initial accumulation

		// initial acucmulation
		for (int j = 0; j < std::min(r, w); j++) // reduce the iteration since we already filled the border when r > w
			acc += rand() % 100;							 // removed ternary operator
	}
}

void no_fill()
{
	srand(time(NULL));
	int r = 2 * 100000, w = 100000, h = 10000;

	for (int i = 0; i < h; i++)
	{

		int acc;

		acc = 66;

		// initial acucmulation
		for (int j = 0; j < r; j++)
			acc += j < w ? rand() % 100 : 55; // removed ternary operator
	}
}

int main()
{
	std::chrono::time_point<std::chrono::steady_clock> start_0 = std::chrono::steady_clock::now();
	fill();
	std::cout << std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start_0).count() << "\n";

	start_0 = std::chrono::steady_clock::now();
	no_fill();
	std::cout << std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start_0).count() << "\n";
	
}
```

**Comment by bfraboni** [comment]
I checked the compiled code this morning, and in the `fill` function:
- O0 calls the std::min function for each loop iteration
- O3 results in an optimized static loop

In the `no_fill` function,
- O0 calls the test for each loop iteration, and there are two separate jumps
- O3 honestly I don't understand the compiled code super well in this case, lots of jumps and tricks ...

But I don't see any perf difference with -O3 or -O0 between the two functions.
To make the comparison more fair, I changed the functions to pass the variables r,w, and h as arguments but it did not changed the perf.

You can check the compiler output here:
https://godbolt.org/z/1s9jhzEsM

**Comment by michelerenzullo** [comment]
Yeah, I had similar results, strangely with O3
 no_fill is a few ms faster, the compiler is probably doing his thing, with O0 fill is faster. Well we can move on so

**Comment by michelerenzullo** [comment]
I just received my good laptop, and I can say that accumulation is faster than opencv blur!
The problem with my old laptop is that accumulation is using more RAM, this affects performance when you have a slow RAM. We should check why it's using double of opencv ram.

EDIT: In my code I'm padding the border by reflection, this increase the size of the image and the memory usage, if I don't padd and I use the standard extend policy I have the same mem usage. 

OpenCV is not padding the border, I think is "reading" in reverse when is out of the border. "mirror" reading in a reverse order will potentially address this issue in future

**Comment by michelerenzullo** [comment]
> The small kernel version has been changed such that the filter loop is divided in 3 loops that allow to remove the ternary operations too (this is what I pushed in the unsafe branch, plus the improvements from point 2 and 3).

Line 134 unsafe branch versus line 145 in function small kernel, it s not corresponding the unsafe version as you said, it s still checking what j<w , buy j is always less than w in this template. Unsafe version is correct, small kernel is not. Take a look :)

**Comment by bfraboni** [comment]
Thanks you for noticing this, my bad, I should not copy/paste/modify code pieces...
I fixed it in the last commit :
 https://github.com/bfraboni/FastGaussianBlur/blob/6462598b32148cf8f2ff6c354cf2a96fa6c67950/fast_gaussian_blur_template.h#L145
I also simplified the loop indices just above.

**Comment by michelerenzullo** [comment]
I'm testing a new code for "kMirror" policy, without increase the length of the input (for padding the reflected pixels) but reading in a reverse way the begin and the end, if you have some thoughts on your previous attempts can be useful tho

**Comment by michelerenzullo** [comment]
https://gist.github.com/michelerenzullo/e6c012b41fc0ab278a523815f14c842e
it works perfectly :) 
"emulating" the reflected padded pixels, without increase the length of the row.

this should become the default implementation

NOTE: the reflection is possible till the center of the image, over that it won't make sense since it's a "super useless blur", r has to be <=w / 2 , I added a check.

Suppose this array
a b c d e f g

And ksize = 5, r = 2
c b _ a b c d e f g _ f e

So if the kernel is bigger , over the center (like a useless super blur)

ksize = 11 , r = 5
f e d c b _ a b c d e f g _ f e d c b <--- it won't produce consistent results

What would be the criteria?
b c d c b _ a b c d e f g _ f e d e f <--- this should be the right implementation, a sort of recursive reflection, for my project I don't need this and I think that also in your code you don't need it

**Comment by bfraboni** [comment]
Great you made the reflection (mirror) working. In fact, once we split the filter loop in 3 different loops, the mirroring can be achieved more easily. That's what I planned to do in the future (wrap and mirror border policies).
Now you made the work easier for me, I'll try to merge it asap (I was moving house this weekend, which took me a lot of time). And I also consider adding the wrap border policy, which is very similar except we read on the other side of the image.  

Regarding the usefulness of the blur, we can test for both the mirror and wrap, as you said if `r < w/2` we call the specific filtering function `horizontal_blur_mirror`/ `horizontal_blur_wrap`, else we can call an arbitrary `kExtend` policy with a warning message, which OK as a default behavior.

I don't have any insights on what would be the best behavior from a signal processing point of view. 
Maybe having a filter radius that overlaps the whole image `r < w` could also be OK. 
Even though its not super useful, it covers all the "small kernels" cases. 
I would have to read OpenCV::borderInterpolate to know how they do when the required pixel to reflect is far away outside the image. Do you know if they apply what you say,  a sort of "recursive reflection" ?

I consider also adding a ` fast_box_blur` function, and reworking the parameters such that the border policy can be passed as an argument.

One question though, why the mirror should become the default implementation ?
Since none of the border strategies is perfectly accurate (we create signal), I think the default choice would go for the less computationally expensive, that is using a constant value.

**Comment by michelerenzullo** [comment]
Mirror is usually the default implementation in any software, OpenCV, Photoshop, and I guess it's the most natural when looking the image, why someone should need a bad looking edges? my implementation it's not really expensive, it's just reading some values two times at the left and right border.  Wrap policy is kinda uncommon, tho.

I didn't check OpenCV yet, I don't know if it's a recursive reflection or just an interpolation, perhaps nearest interpolation? 

Like in the example of before

e e d d c c b b _ a b c d e f g h i j _ i i h h g g f f

In both cases the output is so blur that you don't really spot the difference... Because as I said before "it's kinda useless". Maybe just for academic purposes.

I might have some idea about double accumulation at once, using some leading 0s, if you have some suggestions it will help, so we can do more accumulation (just for simplicity we assume two pass) in one pass instead of twice or more

EDIT3:
I did something similar to what you did when trying to read out of the buffers, I applied a reverse iterator two times, this could affect slighty the performance, not sure but it allows r < w  instead of r < w / 2

EDIT2:
Reflection padding can be extended till r< w without problems. 
In my code I had to set as maximum r < w/2 because otherwise it will try to read in[ri*C+ch] in the right pad that doesn't exist since is "emulated". I can fix this I think

EDIT: 

I tested cv::copyMakeBorder with reflection_101, it's doing backward and forward over and over when reached the end. exmaple:
Base image
![xianyu-hao-LNcf8wJU4zY-unspla_sh](https://user-images.githubusercontent.com/76132686/191057010-e2c220a0-3198-4781-b6fd-c7780ea8ee5c.jpg)
Super reflected over and over image with cv
![c_](https://user-images.githubusercontent.com/76132686/191057016-07510613-7bd5-4ee6-af92-4df3476b61a3.png)

**Comment by michelerenzullo** [comment]
About the double accumulator I finished to code it, basically does 2 accumulation at once using a circular buffer as temp array, and reflect the borders automatically without increasing memory(reflection limitless). Sadly it's slower than expected, doing benchmark it comes out that doing many push and pop with a dequeue every pixel is kinda "expensive", but even if we disable it, playing too much to get the correct index trough "modulo %" slow down the process. I implemented a lookup table to get the correct index position when asking for a pixel to reflect and reduce the "modulo %" operations but that's not enough

Python code:
```py
import numpy as np
import collections

# ksize = 7 r = 3
# input array 200 19 55 44 59 2 4 110 22 4
# padded twice 4 2 59 | 44 55 19 | 200 19 55 44 59 2 4 110 22 4 | 22 110 4 | 2 59 44

# expected / correct outputs
# 1st pass 109 164 183 | 383 398 451 | 436 451 398 383 293 296 245 223 274 276 | 274 223 245 | 241 219 109
# 2nd pass 839 1237 1688 | 2124 2466 2700 | 2900 2810 2708 2502 2289 2112 1990 1881 1811 1760 | 1756 1752 1587 | 1311 1037 814

# output is
# 1st pass 109 164 183 | 383 398 451 | 436 451 398 383 293 296 245 223 274 276 | 274 223 245 | 241 219 109
# 2nd pass 839 1237 1688 | 2124 2466 2700 | 2900 2810 2708 2502 2289 2112 1990 1881 1811 1760 | 1756 1752 1587 | 1311 1037 814

input_data = np.array([200, 19, 55, 44, 59, 2, 4, 110, 22, 4])

ksize = 7  # kernel is odd

radius = int(ksize/2)
print("kernel size:", ksize, "radius:", radius)

x1 = np.array(input_data)
d = collections.deque(maxlen=ksize+1)

print(x1)

sum1 = 0
sum2 = 0

output1 = np.zeros(x1.size, dtype=int)
output2 = np.zeros(x1.size, dtype=int)
d.extend(np.zeros(ksize + 1, dtype=int))

lut = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 8, 7, 6, 5, 4, 3, 2, 1])
for i in range(radius):
    sum1 = sum1 + x1[lut[(ksize-i-1) % lut.size]]

for i in range(radius, ksize):
    sum1 = sum1 + x1[lut[(ksize-i-1) % lut.size]]
    d.append(sum1)
    sum2 = sum2 - d[0] + d[ksize]

for i in range(1, x1.size + radius * 2):
    sum1 = sum1 + x1[lut[i % lut.size]] - x1[lut[(ksize-i) % lut.size]]
    d.append(sum1)
    sum2 = sum2 - d[0] + d[ksize]
    if (i - radius >= 0):
        if (i - radius < x1.size):
            output1[i - radius] = sum1
        if (i - radius*2 >= 0):
            output2[i - radius*2] = sum2

print(output1, "\n", output2)

```

C++ Code:
```c++
template <typename T>
inline void append(std::deque<T>& mydequeue, T param)
{
	mydequeue.pop_front();      // or pop()
	mydequeue.push_back(param); // or push(param)
}

template <typename T, int C>
void horizontal_blur_kernel_reflect_double(const T* in, T* out, const int w, const int h, const int ksize)
{
	// change the local variable types depending on the template type for faster calculations
	using calc_type = std::conditional_t<std::is_integral_v<T>, int, float>;

	int r = 0.5f * (ksize - 1);
	const float iarr2 = 1.f / ((r + r + 1) * (r + r + 1));

	std::vector<int> lut(w * 2 - 2, 0);
	for (int i = 0; i < w; ++i) lut[i] = i;
	std::copy_n(lut.rbegin() + w - 1, w - 2, lut.begin() + w);

	#pragma omp parallel for
	for (int i = 0; i < h; i++)
	{
		const int begin = i * w;
		calc_type acc[C] = {}, acc2[C] = {};        // first value, last value, sliding accumulator

		std::vector<std::deque<calc_type>> d(C, std::deque<calc_type>(ksize + 1, 0));

		for (int j = 0; j < r; ++j)
			for (int ch = 0; ch < C; ++ch)
				acc[ch] = acc[ch] + in[(begin + lut[(ksize - j - 1) % lut.size()]) * C + ch];

		for (int j = r; j < ksize; ++j)
		{
			for (int ch = 0; ch < C; ++ch)
			{
				acc[ch] = acc[ch] + in[(begin + lut[(ksize - j - 1) % lut.size()]) * C + ch];
				append<calc_type>(d[ch], acc[ch]);
				acc2[ch] = acc2[ch] - d[ch][0] + d[ch][ksize];
			}
		}

		for (int j = 1; j < w + r * 2; ++j)
		{
			for (int ch = 0; ch < C; ++ch)
			{
				//NOTE: abs(ksize-j) in C++ rather than (ksize-j) because modulo with negative numbers has a different behaviour from python
				acc[ch] = acc[ch] + in[(begin + lut[j % lut.size()]) * C + ch] - in[(begin + lut[abs(ksize - j) % lut.size()]) * C + ch];
				append<calc_type>(d[ch], acc[ch]);
				acc2[ch] = acc2[ch] - d[ch][0] + d[ch][ksize];
				if (j - r * 2 >= 0)
					out[(begin + j - r * 2) * C + ch] = acc2[ch] * iarr2 + (std::is_integral_v<T> ? 0.5f : 0);
			}
		}
	}
}
```

**Comment by michelerenzullo** [comment]
I close the issue, since I don't see anything else to improve further the performance atm, benchmarks on i7-10750H are good compared to opencv (for me it's like a guideline). To be honest I don't understand what happens around 8250 x 5500px in the graph, I guess something correlated to the cache but my L2 cache is 256K for 6 cores so I don't spot the references.

The double accumulator(or N accumulators) with circular buffer was a good idea but it's not fast as expected sadly, maybe someone can improve further my work or take as base. You can see the above implementation in [my repository](https://github.com/michelerenzullo/FastBoxBlur) defining #DOUBLE_ACCUMULATOR, just for documentation. If something new comes out I'll update you

![bench](https://user-images.githubusercontent.com/76132686/192660534-3d3c909e-e116-4e8b-a275-bb7c7f131a27.png)
